version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wc
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/wc
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=docker


  db:
    image: 'postgres'
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=wc
